version: '3.7'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_elysia
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    networks:
      - my_network

  db:
    image: mysql:5.7
    container_name: hackathon_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hack_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local